[project]
name = "ExtinguiTrack"
version = "1.0.0"
description = "fire extinguisher management system."
authors = "Rodrigo dos Santos Felix"

[default]
DEBUG = true
PERMANENT_SESSION_LIFETIME=3600
SQLALCHEMY_TRACK_MODIFICATIONS = "False"