from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def init_app(app):
    db.init_app(app)


class FireExtinguisher(db.Model):
    fire_extinguisher_id = ...
    serial_number = ...
    manufacturer = ...
    extinguisher_type = ...
    extinguishing_agent = ...
    capacity = ...
    manufacturing_date = ...
    last_inspection_date = ...
    location_id = ...


class Supplier(db.Model):
    supplier_id = ...
    company_name = ...
    phone = ...
    cep = ...
